version: 3

vars:
  PER_YEAR: 1
  GH_ORG: "nim-works"
  TARGET: nimskull
  BRANCH: devel
  TMPD: /tmp
  DB_FILE: /tmp/db.sqlite
  PNG_FILE: /tmp/db.png
  SCRIPT_OPTS: /tmp/db.sqlite /tmp/db.png --config=scripts/config.cfg
  BIN: ./build/bin/code_forensics
  ROOT: |
    {{env "PWD"}}
  REL_CONAN: "build/dependencies/conan"
  CONAN_DIR: |
    {{env "PWD"}}/build/dependencies/conan
  GDB_CMD: gdb
    -batch
    -nx
    -ex "source {{env "PWD"}}/gdb_decorator.py"
    -ex "set print address off"
    -ex "set print frame-arguments none"
    -ex "set print frame-info source-and-location"
    -ex "set filename-display basename"
    -ex "run"
    -ex "bt"
    --args

tasks:
  arch_docker_image:
    desc: "Build a docker test image or re-build if one already exists"
    vars:
      IMAGE: code_forensics_arch

    cmds:
      - ( docker image ls | grep {{.IMAGE}} && docker image rm {{.IMAGE}} ) || true
      - docker image build -t {{.IMAGE}} .

  ensure_deps:
    desc: "Ensure test directory exists"
    status:
      - test -e /tmp/{{.TARGET}}

    cmds:
      - git clone https://github.com/{{.GH_ORG}}/{{.TARGET}}.git /tmp/{{.TARGET}}

  ensure_test_db:
    desc: "Ensure test database exists"
    deps: [ensure_deps]
    status:
      - test -s {{.DB_FILE}}
    cmds:
      - task: debug_run

  burndown:
    deps: [ensure_test_db]
    desc: Build sampled burndown plot
    cmds:
      - "./scripts/table_per_period.py {{.DB_FILE}} {{.PNG_FILE}} --per-year={{.PER_YEAR}}"

  ridgeline:
    deps: [ensure_test_db]
    desc: "Build top commiter activity ridgeline"
    cmds:
      - ./scripts/author_ridgeline.py {{.SCRIPT_OPTS}} --top=10

  authorship:
    deps: [ensure_test_db]
    desc: "Burndown chart for the code ownership"
    cmds:
      - ./scripts/code_authorship.py {{.SCRIPT_OPTS}}

  hotspot_connections:
    deps: [ensure_test_db]
    desc: "Generate connectivity graph for the most edited files"
    cmds:
      - >
        ./scripts/hotspot_connections.py
        {{.DB_FILE}}
        /tmp/db.png
        --top=120
        --config=scripts/config.cfg
        --mode=overwrite
        --ordering-mode=connections

  top_comitter:
    deps: [ensure_test_db]
    desc: "Generate top comitters for the code"
    cmds:
      - ./scripts/top_comitters.py {{.SCRIPT_OPTS}}

  line_category:
    deps: [ensure_test_db]
    desc: "Line category breakdown"
    cmds:
      - ./scripts/line_category.py --subdir-breakdown={{.PER_DIR}} {{.SCRIPT_OPTS}}
    vars:
      PER_DIR: False

  message_length:
    deps: [ensure_test_db]
    desc: "Generate stats for the commit message lenght"
    cmds:
      - ./scripts/commit_message_length.py {{.SCRIPT_OPTS}}

  all_stats:
    deps: [ensure_test_db]
    desc: "Execute all statistics scripts in sequence"
    cmds:
      - >
        ./scripts/all_stats.py
        {{.DB_FILE}}
        {{.TMPD}}
        --config={{.PWD}}/scripts/all_config.yaml
        --subconfig={{.PWD}}/scripts/config.cfg

  compare:
    cmds:
      - ./tests/ci_compare_repo.sh

  build_binary:
    dir: build
    deps: [conan_install]
    desc: "Build build the binary file"
    cmds:
      # - >
      #   cmake --build .. --target clean
      - >
        cmake
        ..
        --trace
        --trace-expand
        --trace-redirect=/tmp/cmake-trace.txt
        # --trace-source=CMakeLists.txt
        # --trace-source=external/hcxx_common/CMakeLists.txt
        # --trace-expand

      - make -j12

  conan_install:
    cmds:
      - conan install . -if {{.REL_CONAN}} --build=missing --settings compiler.libcxx="libstdc++11"
    status:
      - test -e {{.CONAN_DIR}}

  perf_run:
    deps: [build_binary]
    cmds:
      - "perf record {{.BIN}} {{.OPTS}}"
    vars:
      OPTS: /tmp/{{.TARGET}}
        --branch={{.BRANCH}}
        --filter-script=scripts/code_filter.py

  debug_run:
    deps: [build_binary]
    cmds:
      - "{{.BIN}} --help || gdb_cmd {{.BIN}} --help"
      # - "{{.BIN}} {{.OPTS}}"
      - rm -f {{.DB_FILE}}
      - "{{.BIN}} {{.OPTS}} || {{.GDB_CMD}} {{.BIN}} {{.OPTS}}"
      - rm -f /tmp/temp_db.sqlite
      - cp {{.DB_FILE}} /tmp/temp_db.sqlite

    vars:
      OPTS: /tmp/{{.TARGET}}
        --branch={{.BRANCH}}
        --outfile={{.DB_FILE}}
        --filter-script=scripts/code_filter.py
        --filter-args=--per-year={{.PER_YEAR}}
        --filter-args=--target={{.TARGET}}

  build_git_wrapper:
    cmd: clang++ generate_git_wrapper/genwrapper.cpp
      -std=c++2a
      -ferror-limit=1
      -o genwrapper.bin
      -fuse-ld=mold
      -g
      -lclang-cpp
      -lLLVM
      @{{.CONAN_DIR}}/conanbuildinfo.gcc

  docs:
    cmd: doxygen -q Doxyfile

  wrap_git:
    deps: [build_git_wrapper]

  default:
    # deps: [compare]
    # deps: [authorship, burndown]
    # deps: [burndown]
    deps: [debug_run]
