name: "Compile and execute analysis for the current repository on Arch Linux"
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: archlinux:latest
    # defaults:
    #   run:
    #     working-directory: ./code_forensics
    steps:
      - name: "Install git"
        run: |
          pacman --noconfirm -Syu
          pacman --noconfirm -S git
      - name: "Checkout submodules"
        run: |
          echo $PWD
          ls -R .
          ./tests/ci_general_fetch.sh

      - name: "Install remaining dependencies"
        run: ./tests/ci_arch_pacman.sh

      - name: "Install general dependencies"
        run: ./tests/ci_general_deps.sh

      - name: "Build code analyzer"
        run: ./tests/ci_general_build.sh

      - name: "Execute main test commands"
        run: ./tests/ci_general_run.sh

      - uses: actions/upload-artifact@v3
        with:
          name: burndown-plots
          path: |
            *.png
            nimskull_plots/*.png
            nimskull.sqlite
