name: "Compile and execute analysis for the current repository on Arch Linux"
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: archlinux:latest
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v2
      - name: "Update installed packages"
        run: pacman --noconfirm -Syu
      - name: "Install package dependencies"
        run: |
          pacman --noconfirm -S \
            gcc \
            clang \
            python-pip \
            wget \
            curl \
            git \
            cmake \
            make \
            boost

        env:
          DEBIAN_FRONTEND: noninteractive

      - name: "Install conan"
        run: pip install conan matplotlib igraph pandas numpy
      - name: "Install conan dependencies"
        run: |
          conan install . \
            -if build/dependencies/conan \
            --build=missing \
            --settings compiler.libcxx="libstdc++11"

      - name: "Build code analyzer"
        run: |
          mkdir -p build
          cd build
          cmake ..
          make -j10
          cd ..

      - name: "Compare repositories"
        run: ./tests/ci_compare_repo.sh

      - name: "Run all stats"
        run: |
          mkdir nimskull_plots
          ./scripts/all_stats.py \
            nimskull.sqlite \
            nimskull_plots \
            --config=scripts/all_config.yaml \
            --subconfig=scripts/config.cfg

      - uses: actions/upload-artifact@v3
        with:
          name: burndown-plots
          path: |
            *.png
            nimskull_plots/*.png
            nimskull.sqlite
