name: "Compile and execute analysis for the current repository"
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - uses: actions/checkout@v2
      - run: pacman --noconfirm -Syu
      - name: "Install dependencies"
        run: |
          pacman --noconfirm -S \
            gcc \
            clang \
            python-pip \
            wget \
            git \
            cmake \
            make \
            boost

      - name: "Install conan"
        run: pip install conan
      - run: |
          conan install . -if build/dependencies/conan --build=missing
          mkdir build
          cd build
          cmake .. -D "CMAKE_MODULE_PATH=$(PWD)/../build/dependencies/conan"
          make -j10
          cd ..
