name: "Compile and execute analysis for the current repository"
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v2
      - name: "Update installed packages"
        run: sudo apt-get -qq update
      - name: "Install package dependencies"
        run: |
          sudo apt-get -qq -y install \
            cmake git g++ gcc make sudo tar wget curl \
            pip clang libboost-all-dev

        env:
          DEBIAN_FRONTEND: noninteractive

      - name: "Install conan"
        run: pip install conan
      - name: "Build code analyzer"
        run: |
          conan install . \
            -if build/dependencies/conan \
            --build=missing \
            --settings compiler.libcxx="libstdc++11"

          mkdir -p build
          cd build
          cmake ..
          make -j10
          cd ..

      - name: "Compare repositories"
        run: |
          pwd
          ./build/bin/code_forensics --help
          git clone https://github.com/nim-works/nimskull.git /tmp/nimskull
          git clone https://github.com/nim-lang/Nim.git /tmp/nim

          ./build/bin/code_forensics /tmp/nimskull \
            --filter-script=code_filter.py \
            --branch=devel \
            --logfile=nimskull.log \
            --outfile=nimskull.sqlite

          ./build/bin/code_forensics /tmp/nim \
            --filter-script=code_filter.py \
            --branch=devel \
            --logfile=nim.log \
            --outfile=nim.sqlite

          ./scripts/table_per_period.py nimskull.sqlite nimskull.png
          ./scripts/table_per_period.py nim.sqlite nim.png

      - uses: actions/upload-artifact@v3
        with:
          name: burndown-plots
          path: |
            nim.png
            nimskull.png
